name: Development Build
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Delete image
      #   uses: bots-house/ghcr-delete-image-action@v1.0.0
      #   with:
      #     # NOTE: at now only orgs is supported
      #     owner: bots-house
      #     name: some-web-service
      #     # NOTE: using Personal Access Token
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ghcr.io/multipassport/deploy:latest
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/multipassport/deploy:latest
# jobs:
#   backend:
#     runs-on: ubuntu-20.04
#     steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      # - name: Set up remote branch
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/way_up_frontend/ && git branch --set-upstream-to=origin/main"
      # - name: Pull from github
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/way_up_frontend/ && git pull && git reset --hard origin/main"
      # - name: Deploy to development server
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "~/way_up_frontend/deploy.sh"
      -
        name: Login to private registry
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u {{github.actor}} --password-stdin"
      -
        name: Deploy to development server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/way_up_frontend/ && docker compose down -v && docker compose pull && docker compose up -d"
